### ISSUE TITLE
Let's separate the regex into a standalone library and then tap it

### ISSUE THREAD

**Issue by revelt** [sallar/stringz#27]
hi Sallar, guys

Let's separate the regex in `string.js` into a standalone library and then consume it from there. This tight-coupling does no good for the community because regex is way more universal and useful compared to this library (regex + methods). For example, I'm currently not interested in none of the methods in this library (no offence) yet I want the regex for my functions. I'd rather not consume `string.js` directly as-a-file because it's a brittle, non-managed way - everything should be in semver packages.

I think this regex is great because it tackles all these newfangled emoji that go beyond the usual high-surrogate + low-surrogate pattern.

What do you think?

cheers
Roy

**Comment by sallar** [comment]
Hi @revelt that's a great idea. However the Regex is copied from Lodash.js as mentioned in the README, but I think since it's published as MIT, we can actually publish it as a separate package. Although, this will cause `stringz` to not be "no-dep" package anymore... Any ideas about that? What about something like:

```js
import astralRegex from 'stringz/regex';
```

**Comment by revelt** [comment]
I guess if you promise not to move files around without bumping `major` we could `import` it directly...

Feel free to close if you lean towards leaving it as it is.

**Comment by sindresorhus** [comment]
> this will cause stringz to not be "no-dep" package anymore...

That's a silly reason not to do it. It should be a separate package.

**Comment by sallar** [comment]
@sindresorhus you're right. I will release it as a separate package. Any ideas for naming? @revelt

**Comment by revelt** [comment]
https://www.npmjs.com/package/unicode-character-regex
or even
https://www.npmjs.com/package/character-regex
?

I don't know, what you feel suits most..

It's common to append `-regex` to the name. Also, consider search keywords vs. hassle to type balance.
