### ISSUE TITLE
add benchmark?

### ISSUE THREAD

**Issue by derhuerst** [sallar/stringz#7]
Since this is a pretty low-level utility library, it is going to occur a lot at the bottom of stack traces in loops. Therefore good performance is necessary imho.

I propose to put a benchmark in place that compares this library to lodash's functionality and compares it to native JS (which doesn't respect multi-byte chars of course). Also a performance comparison to other unicode-aware string libraries would be nice.

**Comment by derhuerst** [comment]
In particular, a comparison to these might be interesting:

- beaugunderson/emoji-aware
- `lodash.toArray`
- `lodash.split`
- essdot/spliddit
- essdot/spliddit
- substack/utf8-length
- substack/utf8-bytes

**Comment by sallar** [comment]
@derhuerst Thanks. Great idea. There's a side note to this: All of the libraries you’ve mentioned except lodash.toArray get the unicode thing wrong. They don’t work as expected and that’s exactly the reason I made this library. I’m using a regex from lodash and that's probably not fast. But I’ll make sure there’s a benchmark included.

**Comment by sallar** [comment]
There's also this library which gets it wrong: https://github.com/devongovett/grapheme-breaker

**Comment by jacktuck** [comment]
@derhuerst  great idea! I use lodash's toArray at the moment.

Wondering if stringz will be more efficient.

**Comment by sallar** [comment]
@jacktuck @derhuerst I added the benchmarks:

```
Stringz .length (accruate) x 861,039 ops/sec ±1.57% (84 runs sampled)
Lodash .toArray (accruate) x 795,108 ops/sec ±2.13% (82 runs sampled)
Emoji Aware .split (inaccurate) x 2,269 ops/sec ±1.38% (85 runs sampled)
Spliddit .length (inaccurate) x 487,718 ops/sec ±2.21% (83 runs sampled)
UTF8 Length (inaccurate) x 232,918 ops/sec ±1.02% (87 runs sampled)
Fastest is Stringz .length
```

I didn't include String.prototype.length because that would be a bit unfair, but all in all it seems that this library is faster than others. or as fast.
